# Site information
site_name: ARCHIPELAGO | 群岛：雕刻时光
site_url: https://qundao.github.io/
# site_author: 
site_description: ""
copyright: Copyright &copy; 2024 
# docs_dir: docs/

# Repository
# repo_name: qundao.github.io
repo_url: https://github.com/qundao/qundao.github.io
# edit_uri: tree/main

# Theme
theme:
  name: material
  # custom_dir: overrides
  favicon: assets/favicon.ico
  language: "zh"
  icon:
    logo: material/island
    repo: fontawesome/brands/github-alt
  font:
    text: Helvetica Neue, Roboto, sans-serif
    code: Fira Mono, Roboto Mono, monospace
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - content.code.copy

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.pathconverter

extra_javascript:
  - assets/js/audio.js
extra_css:
  - assets/css/audio.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/qundao

plugins:
  - search
  - blog
  - table-reader
  - awesome-pages:
      collapse_single_pages: true
      strict: false

nav:
  - 其内: index.md
  - 其言: 
    - blog/index.md
  - 其器: 
    - tools/index.md
    - ... | flat | tools/*.md
  - 其人: about/index.md
