# Site information
site_name: 群岛：雕刻时光
site_url: https://qundao.github.io/
# site_author:
site_description: "archipelago, sculpting in time"
copyright: Copyright &copy; 2024-2025 | CC BY-4.0
# docs_dir: docs/

# Repository
# repo_name:
# repo_url:
# edit_uri: tree/main

# Theme
theme:
  name: material
  custom_dir: overrides
  favicon: static/favicon.ico
  logo: static/favicon.ico
  # language: "zh"
  icon:
    logo: material/island
    repo: fontawesome/brands/square-github
    edit: material/pencil
    view: material/eye
    tag:
      default: fontawesome/solid/tag
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    # - navigation.expand
    # - navigation.sections
    # - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    # - search.share
    - toc.follow
    # - toc.integrate
    - content.code.copy
    # - content.action.edit
    # - content.action.view
    - header.autohide
  # icon:

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      linenums_style: pymdownx-inline
      linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
    # custom_fences:
    #   - name: mermaid
    #     class: mermaid
    #     format: !
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.pathconverter
  # more
  - mdx_truly_sane_lists
  - markdown_gfm_admonition

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - static/js/katex.js

  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/src/tablesort.min.js
  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/dist/sorts/tablesort.date.min.js
  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/dist/sorts/tablesort.number.min.js
  - static/js/tablesort.js

  - https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/npm/datatables.net@2.0.8/js/dataTables.min.js
  # - https://code.jquery.com/jquery-3.7.1.min.js
  # - https://cdn.datatables.net/2.0.8/js/dataTables.min.js

  - https://unpkg.com/heti/umd/heti-addon.min.js
  - static/js/heti.js
  - https://cdnjs.cloudflare.com/ajax/libs/Han/3.3.0/han.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.min.css
  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/tablesort.min.css
  - https://unpkg.com/heti/umd/heti.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/Han/3.3.0/han.min.css
  - static/css/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/qundao

plugins:
  - search
  - table-reader
  # - awesome-pages:
  #     collapse_single_pages: true
  #     strict: false
  - minify:
      minify_html: true
  - i18n:
      docs_structure: suffix
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true
          site_name: ARCHIPELAGO | SCULPTING IN TIME
          nav_translations:
            首页: Home

nav:
  - 首页:
    - index.md
